[project]
name = "polars_styler"
version = "0.1.0"
description = ""
readme = "README.md"

dependencies = [
    "polars ~= 0.18.2",
    "pyarrow ~= 12.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

