# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run linter
      run: uv run ruff check

    - name: Run tests
      run: |
        uv run pytest py_tests
        uv run python -m doctest polars_styler/**/*.py

    - name: Run tests (with polars 1.10)
      run: |
        uv run --with 'polars~=1.10.0' pytest py_tests
        uv run --with 'polars~=1.10.0' python -m doctest polars_styler/**/*.py

    - name: Run tests (with upgraded libraries)
      run: |
        uv run --upgrade pytest py_tests
        uv run --upgrade python -m doctest polars_styler/**/*.py
